# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 2
    
# e.g. "anas_krystallinus"    
species.name <- "Phylloscopus_sibilatrix"
    
# e.g. "red"    
color <- "blue"
    
# For list of colours available in R, see http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf

usethis::use_git_remote(
  name = "upstream", 
  url = "https://github.com/JJFoest/collaborative_github_exercise.git")

usethis::git_remotes()

usethis::pr_merge_main()
